# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    # base_path: 'https://cdn.ckeditor.com/4.22.1/standard'
    # js_path: 'https://cdn.ckeditor.com/4.22.1/standard/ckeditor.js'
    default_config: full
    configs:
        full:
            toolbar: full

twig:
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@VichUploader/Form/fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'admin2/form/admin2_switch_widget.html.twig'
        - 'admin2/form/product_picker_widget.html.twig'
