security:
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin2:
            pattern: ^/admin
            context: admin_shared
            provider: app_user_provider
            lazy: true
            custom_authenticators:
                - App\Security\Admin2Authenticator
            logout:
                path: admin2_logout
                target: admin2_login

        admin:
            pattern: ^/admin2
            context: admin_shared
            provider: app_user_provider
            lazy: true
            custom_authenticators:
                - App\Security\AdminAuthenticator
            logout:
                path: app_logout
                target: app_login

    password_hashers:
        App\Entity\AdminUser:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\AdminUser
                property: email

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/admin2/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin2, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
