sonata_admin:
    title: 'X-media'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false
    assets:
        extra_stylesheets:
            - bundles/sonatapage/sonata-page.back.min.css
        extra_javascripts:
            - bundles/sonatapage/sonata-page.back.min.js

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
