version: "3.7"
services:

  app:
    build:
      args:
        user: xmedia
        uid: 1000
      context: ./
      dockerfile: php.Dockerfile
    image: xmedia
    container_name: xmedia-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - xmedia

  db:
    image: mysql:8
    container_name: xmedia-db
    restart: unless-stopped
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: xmedia
      MYSQL_ROOT_PASSWORD: test
      MYSQL_PASSWORD: test
      MYSQL_USER: xmedia
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
      - dbvolume:/var/lib/mysql
    networks:
      - xmedia

  nginx:
    image: nginx:alpine
    container_name: xmedia-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - xmedia

networks:
  xmedia:
    driver: bridge

volumes:
  dbvolume:
