alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- cluster_name: db-mysql-fra1-79654
  db_name: defaultdb
  db_user: doadmin
  engine: MYSQL
  name: db-mysql-fra1-79654
  production: true
  version: "8"
envs:
- key: MAILER_DSN
  scope: RUN_AND_BUILD_TIME
  value: ${{ secrets.MAILER_DSN }}
- key: APP_ENV
  scope: RUN_AND_BUILD_TIME
  value: prod
- key: APP_SECRET
  scope: RUN_AND_BUILD_TIME
  value: 5ea3114a349591bd131296e00f21c20a
- key: APP_DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DATABASE_URL
  scope: RUN_AND_BUILD_TIME
  value: ${{ secrets.DATABASE_URL }}
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: x-media
    match:
      authority: {}
      path:
        prefix: /
maintenance: {}
name: xmedia-app
region: fra
services:
- build_command: yarn build
  environment_slug: php
  envs:
  - key: COMPOSER_NO_SCRIPTS
    scope: RUN_AND_BUILD_TIME
    value: "true"
  - key: APP_DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "1"
  github:
    branch: master
    repo: DashaSyvyuk/x-media
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: x-media
  run_command: heroku-php-apache2 public/
  source_dir: /
