sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

index:
    path: /
    controller: App\Controller\HomePageController::index

categories:
    path: /categories/{slug}
    controller: App\Controller\CategoryPageController::getCategory

product:
    path: /products/{id}
    controller: App\Controller\ProductPageController::get

cart:
    path: /cart
    controller: App\Controller\CartController::getCart

order:
    path: /order-create
    controller: App\Controller\OrderPageController::create

post_order:
    path: /order
    controller: App\Controller\OrderPageController::post
    methods: POST

search:
    path: /search
    controller: App\Controller\SearchPageController::getSearch

delivery_and_pay:
    path: /delivery-and-pay
    controller: App\Controller\DeliveryAndPayController::index

post_comment:
    path: /comment
    controller: App\Controller\CommentController::post
    methods: POST
