index:
    path: /
    controller: App\Controller\HomePageController::index

categories:
    path: /categories/{slug}
    controller: App\Controller\CategoryPageController::getCategory

product:
    path: /products/{id}
    controller: App\Controller\ProductPageController::get

cart:
    path: /cart
    controller: App\Controller\CartController::getCart

order:
    path: /order-create
    controller: App\Controller\OrderPageController::create

post_order:
    path: /order
    controller: App\Controller\OrderPageController::post
    methods: POST
