index:
    path: /
    controller: App\Controller\HomePageController::index

categories:
    path: /categories/{slug}
    controller: App\Controller\CategoryPageController::getCategory

product:
    path: /products/{id}
    controller: App\Controller\ProductPageController::getProduct

cart:
    path: /cart
    controller: App\Controller\CartController::getCart

mobile_cart:
    path: /shopping-cart
    controller: App\Controller\CartController::getMobileCart

order:
    path: /order-create
    controller: App\Controller\OrderPageController::index

post_order:
    path: /order
    controller: App\Controller\OrderPageController::post
    methods: POST

search:
    path: /search
    controller: App\Controller\SearchPageController::getSearch

search_category:
    path: /search/{categorySlug}
    controller: App\Controller\SearchPageController::getSearch

delivery_and_pay:
    path: /delivery-and-pay
    controller: App\Controller\DeliveryAndPayController::index

warranty:
    path: /warranty
    controller: App\Controller\WarrantyController::index

post_comment:
    path: /comment
    controller: App\Controller\CommentController::post
    methods: POST

about_us:
    path: /about-us
    controller: App\Controller\AboutUsController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

feedback:
    path: /feedbacks
    controller: App\Controller\FeedbackPageController::index
    methods: GET

error:
    path: /404
    controller: App\Controller\ErrorController::show

post_feedback:
    path: /feedbacks
    controller: App\Controller\FeedbackPageController::post
    methods: POST

nova_poshta_office:
    path: /nova-poshta-office
    controller: App\Controller\NovaPoshtaOfficeController::index

sign_up:
    path: /sign-up
    controller: App\Controller\SignUpController::index
    methods: GET

post_sign_up:
    path: /sign-up
    controller: App\Controller\SignUpController::post
    methods: POST

account:
    path: /account
    controller: App\Controller\AccountController::index
    methods: GET

account_contact:
    path: /account/contacts
    controller: App\Controller\AccountContactController::index
    methods: GET

login:
    path: /login
    controller: App\Controller\LoginController::index
    methods: GET

post_login:
    path: /login
    controller: App\Controller\LoginController::post
    methods: POST

post_user:
    path: /user
    controller: App\Controller\UserController::post
    methods: POST

logout:
    path: /logout
    controller: App\Controller\LogoutController::post
    methods: POST

orders:
    path: /account/orders
    controller: App\Controller\MyOrderController::index
    methods: GET

orders_detail:
    path: /account/orders/{id}
    controller: App\Controller\MyOrderController::getOrder

restore_password:
    path: /restore-password
    controller: App\Controller\RestorePasswordController::index
    methods: GET

post_restore_password:
    path: /restore-password
    controller: App\Controller\RestorePasswordController::post
    methods: POST

update_password:
    path: /update-password
    controller: App\Controller\UpdatePasswordController::index
    methods: GET

post_update_password:
    path: /update-password
    controller: App\Controller\UpdatePasswordController::post
    methods: POST

confirm_email:
    path: /confirm-email
    controller: App\Controller\ConfirmEmailController::index
    methods: GET

api_filter_attributes:
    path: /api/v1/filter/{id}/filter_attributes
    controller: App\Controller\API\FilterAttributeController::get

promotion:
    path: /promotion/{slug}
    controller: App\Controller\PromotionController::getPromotion

promotion_category:
    path: /promotion/{slug}/{categorySlug}
    controller: App\Controller\PromotionController::getPromotion

delivery_type:
    path: /delivery-type/{id}
    controller: App\Controller\API\DeliveryTypeController::getItem

thank_you:
    path: /thank-you
    controller: App\Controller\ThankYouController::index
    methods: GET
