index:
    path: /
    controller: App\Controller\HomePageController::index

categories:
    path: /categories/{slug}
    controller: App\Controller\CategoryPageController::get

product:
    path: /products/{id}
    controller: App\Controller\ProductPageController::get
