# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [ ~, App\Entity\Category, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Категорії }

    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [ ~, App\Entity\Product, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Товари }

    admin.product_image:
        class: App\Admin\ProductImageAdmin
        arguments: [ ~, App\Entity\ProductImage, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Картинки, show_in_dashboard: false }

    admin.slider:
        class: App\Admin\SliderAdmin
        arguments: [ ~, App\Entity\Slider, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Слайдер, label: Слайдер }

    admin.filter:
        class: App\Admin\FilterAdmin
        arguments: [ ~, App\Entity\Filter, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Фільтри, label: Фільтри }

    admin.filter_attribute:
        class: App\Admin\FilterAttributeAdmin
        arguments: [ ~, App\Entity\FilterAttribute, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Фільтри, label: Параметри фільтрів, show_in_dashboard: false }

    admin.product_characteristic:
        class: App\Admin\ProductCharacteristicAdmin
        arguments: [ ~, App\Entity\ProductCharacteristic, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Контент, label: Характеристики, show_in_dashboard: false }

    admin.setting:
        class: App\Admin\SettingAdmin
        arguments: [ ~, App\Entity\Setting, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Налаштування, label: Налаштування, show_in_dashboard: true }

    admin.currency:
        class: App\Admin\CurrencyAdmin
        arguments: [ ~, App\Entity\Currency, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Налаштування, label: Курс валют, show_in_dashboard: true }